### ISSUE TITLE
容器序列化时返回内容错误

### ISSUE THREAD

**Issue by edwardpro** [smartbuf/smartbuf-java#1]
如果是一个容器比如：
List<ClassA>

反序列化用：
SmartPacket.deserialize(a, List.class);
返回值为：
[{"stable":true},{"stable":true}]

这种容器只有使用TypeRef才能work

**Comment by sisyphsu** [comment]
泛型必须使用TypeRef来指定，因为SmartPacket不知道List内部元素的类型，它就按照Object来解析。

类似于解析JSON，如果想解析List也必须通过TypeReference指定泛型类型。
